### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by galaxytwenty** [DidntPot/ThrowableFireballs-PMMP#1]
Hey this plugin not working with 1.16.220

**Comment by DidntPot** [comment]
Fixed enjoy

**Comment by galaxytwenty** [comment]
Nice i Try :) 

Thx.

**Comment by galaxytwenty** [comment]
i have try it, but the fireballs disapears a litl later when i throw it, can u make that the fireballs fly a lil time longer ?.

Thx and Nice Plugin.,

**Comment by galaxytwenty** [comment]
have you send per Discord a request. it looks like when i throw the ball on Obsidian then explode the ball,
when i trow it on quarz or another then disapears the ball.
